resources:
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git

- name: smb-broker-kpack-image
  type: s3
  source:
    region_name: us-east-2
    bucket: smb-broker-k8s-images
    versioned_file: smb-broker.tgz
    initial_version: "0"
    access_key_id: {{smb-broker-k8s-images-bucket-access_aws_ID}}
    secret_access_key: {{smb-broker-k8s-images-bucket-access_aws_secret}}

- name: smb-volume-k8s-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/smb-volume-k8s-release
    branch: master
    private_key: {{smb-broker-k8s-github-deploy-key}}

- name: cloudfoundry-cnb-bionic-image
  type: docker-image
  source:
    repository: cloudfoundry/cnb
    tag: bionic

- name: smb-broker-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-broker
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-csi-driver-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-csi-driver
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-release-version
  type: semver
  source:
    access_key_id: {{smb-release-k8s-uploader_aws_ID}}
    bucket: smb-release-versions-k8s
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{smb-release-k8s-uploader_aws_secret}}

jobs:
- name: smb-broker-unit-tests
  serial: true
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - in_parallel:
        fail_fast: true
        steps:
        - task: unit-tests-latest
          tags: [kind]
          attempts: 3
          file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
          privileged: true
          output_mapping:
            built-images: built-latest-images
        - task: unit-tests-1.16
          tags: [kind]
          attempts: 3
          file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
          privileged: true
          params:
            K8S_IMAGE: kindest/node:v1.16.4
        - task: unit-tests-1.15
          tags: [kind]
          attempts: 3
          file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
          privileged: true
          params:
            K8S_IMAGE: kindest/node:v1.15.7
    - put: smb-broker-kpack-image
      params:
        file: built-latest-images/smb-broker.tgz

- name: smb-csi-driver-units
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: run-test
      attempts: 3
      privileged: true
      file: smb-volume-k8s-release/smb-csi-driver/ci/unit-tests.yml

- name: integration-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
      passed:
        - smb-broker-unit-tests
        - smb-csi-driver-units
        - smb-csi-driver-e2e-tests
    - get: smb-broker-kpack-image
      passed:
        - smb-broker-unit-tests
    - task: run-test
      tags: [kind]
      attempts: 3
      privileged: true
      file: smb-volume-k8s-release/ci/integration-tests.yml

- name: smb-csi-driver-e2e-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - in_parallel:
        fail_fast: true
        steps:
        - task: e2e-tests-latest
          tags: [kind]
          attempts: 3
          privileged: true
          file: smb-volume-k8s-release/smb-csi-driver/ci/e2e-tests.yml
        - task: e2e-tests-1.16
          tags: [kind]
          attempts: 3
          privileged: true
          params:
            K8S_IMAGE: kindest/node:v1.16.4
          file: smb-volume-k8s-release/smb-csi-driver/ci/e2e-tests.yml
        - task: e2e-tests-1.15
          tags: [kind]
          attempts: 3
          privileged: true
          file: smb-volume-k8s-release/smb-csi-driver/ci/e2e-tests.yml
          params:
            K8S_IMAGE: kindest/node:v1.15.7
            VOLUME_MODE_SUITE: false

- name: create-github-tag
  serial: true
  plan:
    - get: smb-volume-k8s-release
      trigger: true
      passed:
        - integration-tests
    - get: smb-release-version
      params:
        bump: minor
    - get: smb-broker-kpack-image
      passed:
      - integration-tests
    - put: smb-volume-k8s-release
      params:
        repository: smb-volume-k8s-release
        tag: smb-release-version/version
        only_tag: true
    - put: smb-release-version
      params:
        bump: minor

- name: build-smb-broker-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
      - create-github-tag
      trigger: true
    - get: smb-release-version
      passed:
      - create-github-tag
    - get: smb-broker-kpack-image
      passed:
        - create-github-tag
    - put: smb-broker-docker-image
      tags: [kind]
      params:
        load_repository: localhost:5000/cfpersi/smb-broker
        load_file: smb-broker-kpack-image/smb-broker.tgz
        load_tag: local-test
        tag_file: smb-release-version/version
        tag_as_latest: true

- name: build-smb-csi-driver-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
        - create-github-tag
      trigger: true
    - get: smb-release-version
      passed:
        - create-github-tag
    - put: smb-csi-driver-docker-image
      tags: [kind]
      params:
        tag_file: smb-release-version/version
        tag_as_latest: true
        build: smb-volume-k8s-release/smb-csi-driver

- name: update-golang-version-for-test
  plan:
    - get: cf-acceptance-tests
    - get: cloudfoundry-cnb-bionic-image
      trigger: true
    - get: smb-volume-k8s-release
    - task: extract-version
      file: smb-volume-k8s-release/smb-broker/ci/extract-version.yml
      privileged: true
    - task: commit-and-push
      config:
        inputs:
          - name: smb-volume-k8s-release
          - name: go-version
        outputs:
          - name: modified-repo
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
        run:
          path: bash
          args:
            - -exc
            - |
              go_version=$(cat go-version/go-version)
              old_go_version=$(cat smb-volume-k8s-release/ci/dockerfiles/tests/go-version)
              git clone smb-volume-k8s-release modified-repo
              if [[ "$go_version" == "$old_go_version" ]]; then exit 0; fi
              cp go-version/go-version modified-repo/ci/dockerfiles/tests/go-version
              cd modified-repo
              git add ./ci/dockerfiles/tests/go-version
              git config --global user.email "cf-volume-services@pivotal.io"
              git config --global user.name "CI Bot"
              git commit -m "update go version to ${go_version} [skip ci]"
    - put: smb-volume-k8s-release
      params:
        repository: modified-repo