shared_functions:
  - on_failure: &destroy_cluster
      do:
        - task: wait-1-hour
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: alpine}
            run:
              path: sleep
              args: [ 3600 ]
        - task: destroy-cluster
          file: smb-volume-k8s-release/ci/destroy-cluster.yml
          params:
            GCP_KEY: ((gcp_service_account_key))
            AWS_ACCESS_KEY_ID: {{route53-updater_aws_ID}}
            AWS_SECRET_ACCESS_KEY: {{route53-updater_aws_secret}}
            AWS_DEFAULT_REGION: us-east-1
            AWS_HOSTED_ZONE: {{route53-aws-hosted-zone}}

resources:
- name: cf-volume-services-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-volume-services-acceptance-tests.git

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci
    branch: master

- name: smb-broker-kpack-image
  type: s3
  source:
    region_name: us-east-2
    bucket: smb-broker-k8s-images
    versioned_file: smb-broker.tgz
    initial_version: "0"
    access_key_id: {{smb-broker-k8s-images-bucket-access_aws_ID}}
    secret_access_key: {{smb-broker-k8s-images-bucket-access_aws_secret}}

- name: smb-csi-driver-kpack-image
  type: s3
  source:
    region_name: us-west-1
    bucket: smb-csi-driver-k8s-images
    versioned_file: smb-csi-driver.tgz
    initial_version: "0"
    access_key_id: {{smb-csi-driver-k8s-images-bucket-access_aws_ID}}
    secret_access_key: {{smb-csi-driver-k8s-images-bucket-access_aws_secret}}

- name: smb-volume-k8s-release
  type: git
  source:
    branch: master
    username: {{github-user}}
    password: {{github-password}}
    uri: https://github.com/cloudfoundry/smb-volume-k8s-release.git

- name: smb-csi-driver
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/smb-csi-driver.git
    private_key: {{smb-csi-driver-deploy-key}}

- name: cf-for-k8s
  type: git
  source:
    uri: http://github.com/cloudfoundry/cf-for-k8s
    branch: master

- name: cloudfoundry-cnb-bionic-image
  type: docker-image
  source:
    repository: cloudfoundry/cnb
    tag: bionic

- name: smb-broker-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-broker
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-csi-driver-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-csi-driver
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-release-version
  type: semver
  source:
    access_key_id: {{smb-release-k8s-uploader_aws_ID}}
    bucket: smb-release-versions-k8s
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{smb-release-k8s-uploader_aws_secret}}

jobs:

- name: pats
  on_failure: *destroy_cluster
  on_error: *destroy_cluster
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: cf-for-k8s
        trigger: true
      - get: smb-csi-driver-docker-image
        trigger: true
        passed:
        - build-smb-csi-driver-docker-image
      - get: smb-broker-docker-image
        trigger: true
        passed:
        - build-smb-broker-docker-image
      - get: cf-volume-services-acceptance-tests
      - get: persi-ci
      - get: smb-volume-k8s-release
  - task: deploy-cf
    file: smb-volume-k8s-release/ci/deploy-release.yml
    params:
      GCP_KEY: ((gcp_service_account_key))
      AWS_ACCESS_KEY_ID: {{route53-updater_aws_ID}}
      AWS_SECRET_ACCESS_KEY: {{route53-updater_aws_secret}}
      AWS_DEFAULT_REGION: us-east-1
      AWS_HOSTED_ZONE: {{route53-aws-hosted-zone}}
  - task: generate-pats-config-smb
    file: persi-ci/scripts/ci/generate_pats_config_cf4k8s.build.yml
    params:
      CF_USERNAME: admin
      BROKER_URL: "http://smb-broker.cf-smb"
      BROKER_USER: "foo"
      BROKER_PASSWORD: "foo"
      CREATE_CONFIG: "{\"share\":\"((smb_cats_remote_path))\",\"username\":\"((smb_cats_username))\",\"password\":\"((smb_cert_password))\"}"
      PLAN_NAME: Existing
      SERVICE_NAME: SMB
      BIND_CONFIG: "[\"{}\"]"
    output_mapping:
      pats-config: smb-pats-config
  - task: run-pats-smb
    input_mapping:
      pats-config: smb-pats-config
    file: persi-ci/scripts/ci/run-pats.build.yml
    attempts: 3
    params:
      PARALLEL_NODES: 2
      TEST_MOUNT_OPTIONS: false
      TEST_MOUNT_FAIL_LOGGING: false
      TEST_MULTI_CELL: false
      TEST_READ_ONLY: false
      TEST_DOCKER_PORA: true
  - task: destroy-cluster
    file: smb-volume-k8s-release/ci/destroy-cluster.yml
    params:
      GCP_KEY: ((gcp_service_account_key))
      AWS_ACCESS_KEY_ID: {{route53-updater_aws_ID}}
      AWS_SECRET_ACCESS_KEY: {{route53-updater_aws_secret}}
      AWS_DEFAULT_REGION: us-east-1
      AWS_HOSTED_ZONE: {{route53-aws-hosted-zone}}

- name: smb-broker-unit-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - in_parallel:
        fail_fast: true
        steps:
        - task: unit-tests-latest
          tags: [kind]
          file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
          privileged: true
          output_mapping:
            built-images: built-latest-images
        - task: unit-tests-1.16
          tags: [kind]
          file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
          privileged: true
          params:
            K8S_IMAGE: kindest/node:v1.16.4
        - task: unit-tests-1.15
          tags: [kind]
          file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
          privileged: true
          params:
            K8S_IMAGE: kindest/node:v1.15.7
    - put: smb-broker-kpack-image
      params:
        file: built-latest-images/smb-broker.tgz

- name: smb-csi-driver-units
  plan:
    - get: smb-csi-driver
      trigger: true
    - task: run-test
      privileged: true
      file: smb-csi-driver/ci/unit-tests.yml

- name: bump-csi-driver-submodule
  plan:
    - in_parallel:
        fail_fast: true
        steps:
          - get: persi-ci
          - get: smb-volume-k8s-release
          - get: smb-csi-driver
            passed:
              - smb-csi-driver-units
              - smb-csi-driver-e2e-tests
              - smb-csi-driver-e2e-tests-kustomize
            trigger: true
    - task: bump-submodule
      file: persi-ci/scripts/ci/bump_submodule.build.yml
      input_mapping:
        release-repo: smb-volume-k8s-release
        submodule-repo: smb-csi-driver
      params:
        SUBMODULE_PATH: smb-csi-driver
    - put: smb-volume-k8s-release
      params:
        repository: bumped-repo
        rebase: true

- name: integration-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
      passed:
        - smb-broker-unit-tests
        - bump-csi-driver-submodule
    - get: smb-broker-kpack-image
      passed:
        - smb-broker-unit-tests
    - get: smb-csi-driver-kpack-image
      passed:
        - smb-csi-driver-e2e-tests
    - task: run-test
      tags: [kind]
      privileged: true
      file: smb-volume-k8s-release/ci/integration-tests.yml

- name: smb-csi-driver-e2e-tests
  plan:
    - get: smb-csi-driver
      trigger: true
    - in_parallel:
        fail_fast: true
        steps:
        - task: e2e-tests-latest
          tags: [kind]
          privileged: true
          output_mapping:
            built-images: built-latest-images
          file: smb-csi-driver/ci/e2e-tests.yml
        - task: e2e-tests-1.16
          tags: [kind]
          privileged: true
          params:
            K8S_IMAGE: kindest/node:v1.16.4
          file: smb-csi-driver/ci/e2e-tests.yml
        - task: e2e-tests-1.15
          tags: [kind]
          privileged: true
          file: smb-csi-driver/ci/e2e-tests.yml
          params:
            K8S_IMAGE: kindest/node:v1.15.7
            VOLUME_MODE_SUITE: false
    - put: smb-csi-driver-kpack-image
      params:
        file: built-latest-images/smb-csi-driver.tgz

- name: smb-csi-driver-e2e-tests-kustomize
  plan:
    - get: smb-csi-driver
      trigger: true
    - in_parallel:
        fail_fast: true
        steps:
          - task: e2e-tests-latest
            tags: [kind]
            privileged: true
            file: smb-csi-driver/ci/e2e-tests.yml
            params:
              USE_KUSTOMIZE: true

- name: log-forwarder-unit-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: unit-tests
      tags: [kind]
      file: smb-volume-k8s-release/log-forwarder/ci/unit-tests.yml

- name: build-log-forwarder-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
        - log-forwarder-unit-tests
      trigger: true
    - task: build-image
      privileged: true
      tags: [kind]
      file: smb-volume-k8s-release/log-forwarder/ci/build-docker-image.yml
      params:
        DOCKER_USER: {{dockerhub_username}}
        DOCKER_PASSWORD: {{dockerhub_password}}

- name: bump-rc-version
  serial: true
  plan:
    - get: smb-volume-k8s-release
      trigger: true
      passed:
        - integration-tests
    - get: smb-release-version
      params:
        pre: rc
    - get: smb-broker-kpack-image
      passed:
      - integration-tests
    - get: smb-csi-driver-kpack-image
      passed:
        - integration-tests
    - put: smb-release-version
      params:
        pre: rc

- name: build-smb-broker-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
      - bump-rc-version
      trigger: true
    - get: smb-release-version
      passed:
      - bump-rc-version
      trigger: true
    - get: smb-broker-kpack-image
      passed:
        - bump-rc-version
    - put: smb-broker-docker-image
      tags: [kind]
      params:
        load_repository: localhost:5000/cfpersi/smb-broker
        load_file: smb-broker-kpack-image/smb-broker.tgz
        load_tag: local-test
        tag_file: smb-release-version/version
        tag_as_latest: true

- name: build-smb-csi-driver-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
        - bump-rc-version
      trigger: true
    - get: smb-release-version
      passed:
        - bump-rc-version
      trigger: true
    - get: smb-csi-driver-kpack-image
      passed:
        - bump-rc-version
    - put: smb-csi-driver-docker-image
      tags: [kind]
      params:
        load_repository: localhost:5000/cfpersi/smb-csi-driver
        load_file: smb-csi-driver-kpack-image/smb-csi-driver.tgz
        load_tag: local-test
        tag_file: smb-release-version/version
        tag_as_latest: true

- name: update-golang-version-for-test
  plan:
    - get: cf-volume-services-acceptance-tests
    - get: cloudfoundry-cnb-bionic-image
      trigger: true
    - get: smb-volume-k8s-release
    - task: extract-version
      file: smb-volume-k8s-release/smb-broker/ci/extract-version.yml
      privileged: true
    - task: commit-and-push
      config:
        inputs:
          - name: smb-volume-k8s-release
          - name: go-version
        outputs:
          - name: modified-repo
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
        run:
          path: bash
          args:
            - -exc
            - |
              go_version=$(cat go-version/go-version)
              old_go_version=$(cat smb-volume-k8s-release/ci/dockerfiles/tests/go-version)
              git clone smb-volume-k8s-release modified-repo
              if [[ "$go_version" == "$old_go_version" ]]; then exit 0; fi
              cp go-version/go-version modified-repo/ci/dockerfiles/tests/go-version
              cd modified-repo
              git add ./ci/dockerfiles/tests/go-version
              git config --global user.email "cf-volume-services@pivotal.io"
              git config --global user.name "CI Bot"
              git commit -m "update go version to ${go_version} [skip ci]"
    - put: smb-volume-k8s-release
      params:
        repository: modified-repo
