resources:

- name: nightly
  type: time
  source:
    start: 12:00 AM
    stop: 1:00 AM
    location: America/Los_Angeles

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci
    branch: master

- name: fork-git-resource-docker-image
  type: docker-image
  source:
    repository: cfpersi/fork-git-resource
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: mapfs-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/mapfs-tests
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: nfs-driver-integration-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/nfs-integration-tests
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: bosh-release-test-docker-image
  type: docker-image
  source:
    repository: cfpersi/bosh-release-tests
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: nfs-unit-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/nfs-unit-tests
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-unit-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-unit-tests
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: nfs-cats-docker-image
  type: docker-image
  source:
    repository: cfpersi/nfs-cats
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-k8s-pats-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-k8s-pats
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-k8s-kind-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-k8s-kind-tests
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: cnb-cifs-run-stack-docker-image
  type: docker-image
  source:
    repository: cfpersi/cnb-cifs-run-stack
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: cnb-run-stack-docker-image
  type: docker-image
  source:
    repository: cloudfoundry/run
    tag: base-cnb

- name: smb-volume-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/smb-volume-release.git

- name: nfs-volume-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/nfs-volume-release.git

- name: mapfs-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mapfs-release.git

- name: smb-volume-k8s-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/smb-volume-k8s-release.git

- name: fork-git-resource
  type: git
  source:
    uri: https://github.com/cloudfoundry/go-git-resource.git

jobs:

- name: build-fork-git-resource-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: fork-git-resource
      trigger: true
    - put: fork-git-resource-docker-image
      params:
        build: fork-git-resource
        dockerfile: fork-git-resource/dockerfiles/ubuntu/Dockerfile

- name: build-cnb-cifs-run-stack-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: smb-volume-k8s-release
      trigger: true
    - get: cnb-run-stack-docker-image
      trigger: true
    - put: cnb-cifs-run-stack-docker-image
      params:
        build: smb-volume-k8s-release/smb-csi-driver/cnb-run-stack-dockerfiles

- name: build-nfs-driver-integration-tests-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: nfs-volume-release
      trigger: true
    - put: nfs-driver-integration-tests-docker-image
      params:
        build: nfs-volume-release/dockerfiles/nfs-integration-tests

- name: build-bosh-release-test-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: persi-ci
      trigger: true
    - put: bosh-release-test-docker-image
      params:
        build: persi-ci/dockerfiles/bosh-release-tests

- name: build-nfs-unit-tests-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: nfs-volume-release
      trigger: true
    - put: nfs-unit-tests-docker-image
      params:
        build: nfs-volume-release/dockerfiles/nfs-unit-tests

- name: build-nfs-cats-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: nfs-volume-release
      trigger: true
    - put: nfs-cats-docker-image
      params:
        build: nfs-volume-release/dockerfiles/nfs-cats

- name: build-mapfs-tests-docker-image
  plan:
  - get: nightly
    trigger: true
  - get: mapfs-release
    trigger: true
  - put: mapfs-tests-docker-image
    params:
      build: mapfs-release/dockerfiles/tests

- name: build-smb-unit-tests-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: smb-volume-release
      trigger: true
    - put: smb-unit-tests-docker-image
      params:
        build: smb-volume-release/dockerfiles/smb-unit-tests

- name: build-smb-k8s-kind-tests-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: smb-volume-k8s-release
      trigger: true
    - put: smb-k8s-kind-tests-docker-image
      params:
        build: smb-volume-k8s-release/ci/dockerfiles/tests/

- name: build-smb-k8s-pats-docker-image
  plan:
    - get: nightly
      trigger: true
    - get: smb-volume-k8s-release
      trigger: true
    - put: smb-k8s-pats-docker-image
      params:
        build: smb-volume-k8s-release/ci/dockerfiles/pats/