groups:
- name: all-jobs
  jobs:
  - smb-broker-unit-tests
  - build-smb-broker-docker-image

resources:
- name: smb-volume-k8s-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/smb-volume-k8s-release
    branch: master
    private_key: {{smb-broker-k8s-github-deploy-key}}

- name: smb-broker-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-broker
    username: ((dockerhub_username))
    password: ((dockerhub_password))


- name: smb-broker-version
  type: semver
  source:
    access_key_id: {{smb-broker-k8s-uploader_aws_ID}}
    bucket: smb-broker-versions-k8s
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{smb-broker-k8s-uploader_aws_secret}}

jobs:
- name: smb-broker-unit-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: unit-tests
      file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
    - get: smb-broker-version
      params:
        bump: minor
    - put: smb-volume-k8s-release
      params:
        repository: smb-volume-k8s-release
        tag: smb-broker-version/version
        only_tag: true
    - put: smb-broker-version
      params:
        bump: minor


- name: build-smb-broker-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
      - smb-broker-unit-tests
      trigger: true
    - get: smb-broker-version
      passed:
      - smb-broker-unit-tests
    - put: smb-broker-docker-image
      params:
        tag_file: smb-broker-version/version
        tag_as_latest: true
        build: smb-volume-k8s-release/smb-broker
