resource_types:
  - name: go-mod-vendor-tidy-git
    type: docker-image
    source:
      repository: cfpersi/fork-git-resource
      tag: latest

resources:
- name: nfsv3driver
  type: go-mod-vendor-tidy-git
  source:
    uri: git@github.com:cloudfoundry/nfsv3driver.git
    private_key: {{deployments-persi-key}}

- name: nfs-volume-release
  type: git
  source:
    branch: master
    username: {{github-user}}
    password: {{github-password}}
    uri: https://github.com/cloudfoundry/nfs-volume-release.git

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git

- name: mapfs-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mapfs-release.git

jobs:
- name: unit-test
  public: true
  plan:
  - get: nfsv3driver
    trigger: true
  - task: build
    file: nfsv3driver/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: nfsv3driver
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: nfsv3driver

- name: release-job-tests
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: mapfs-release
      - get: nfs-volume-release
      - get: nfsv3driver
        passed:
        - security-scan
        trigger: true
  - task: bump-submodule
    file: persi-ci/scripts/ci/bump_submodule.build.yml
    input_mapping:
      release-repo: nfs-volume-release
      submodule-repo: nfsv3driver
    params:
      SUBMODULE_PATH: src/code.cloudfoundry.org/nfsv3driver
  - task: rspec
    file: persi-ci/scripts/ci/run-rspec.build.yml
    input_mapping:
      test-repo: bumped-repo
  - task: bosh-release-test
    attempts: 3
    input_mapping:
      nfs-volume-release: bumped-repo
      nfs-volume-release-concourse-tasks: bumped-repo
    file: nfs-volume-release/scripts/ci/run_bosh_release_tests.build.yml
    privileged: true
    tags: [ vol-svc ]
  - put: nfs-volume-release
    params:
      repository: bumped-repo
      rebase: true
