---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfpersi/cf-deployment-concourse-tasks-yq
    tag: latest

inputs:
- name: persi-ci
- name: bbl-state

outputs:
- name: generated-vpn-client-tile-product-config

run:
  path: persi-ci/scripts/ci/generate_vpn_client_tile_product_config

params:
  BBL_ENV: ~
