---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: persi-ci
- name: director-state

outputs:
- name: pats-config

params:
  BBL_STATE_DIR:

  APPS_DOMAIN: replace-me
  CF_API_ENDPOINT: replace-me
  CF_USERNAME: replace-me

  BIND_BOGUS_CONFIG:
  BIND_CONFIG:
  BROKER_PASSWORD_KEY:
  BROKER_URL:
  BROKER_USER:
  CREATE_BOGUS_CONFIG:
  CREATE_CONFIG:
  CREATE_LAZY_UNMOUNT_CONFIG:
  DISALLOWED_LDAP_BIND_CONFIG:
  LAZY_UNMOUNT_VM_INSTANCE:
  PLAN_NAME: replace-me
  SERVICE_NAME: replace-me
  TEST_ISOLATION_SEGMENT:

run:
  path: persi-ci/scripts/ci/generate_pats_config.sh
