---
platform: linux

rootfs_uri: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: persi-ci
  - name: cephfs-bosh-release-tarball

outputs:
  - name: runtime-config-out

params: {}

run:
  path: persi-ci/scripts/ci/update_runtime_config.sh
