---
platform: linux

rootfs_uri: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: persi-ci
  - name: cephfs-bosh-release-tarball
  - name: efs-volume-release-tarball
  - name: local-volume-release-tarball
  - name: nfs-volume-release-tarball

outputs:
  - name: runtime-config-out

params:
  LDAP_SVC_USER: ""
  LDAP_SVC_PASS: ""
  LDAP_HOST: ""
  LDAP_PORT: 389
  LDAP_PROTO: tcp
  LDAP_USER_FQDN: ""


run:
  path: persi-ci/scripts/ci/update_runtime_config.sh
